import 'package:get/get.dart';

class Strings extends Translations{
  @override

  Map<String, Map<String, String>> get keys =>{
    'ar':{
      'language':'اللغة',
      'arabic':'االعربية',
      'english':'الانجليزية',
      'parkinson':'الباركنسون',
      'best_doctor_appointment_app':'أفضل تطبيق لحجز المواعيد الطبية',
      'manage_schedule':'قم بإدارة وجدولة جميع مواعيدك الطبية بسهولة مع Docdoc للحصول على تجربة جديدة.',
      'get_started':'ابدأ الآن',
      'welcome_back':'مرحباً بعودتك',
      'we_are_excited':'نحن متحمسون لعودتك، ولا يسعنا الانتظار لرؤية ما كنت تفعله منذ آخر تسجيل دخول لك',
      'email':'البريد الاكتروني',
      'password':'كلمة المرور',
      'valid_email':'يرجى ادخال بريد الاكتروني فعال',
      'password_terms':'يرجى الالتزام بشروط كلمة المرور',
      'forgot_password':'هل نسيت كلمة السر ؟',
      'login':'تسجيل الدخول',
      'lowercase_letter':'حرف صغير واحد على الأقل',
      'uppercase_letter':'حرف كبير واحد على الأقل',
      'special_character':'رمز خاص واحد على الأقل',
      'number':'رقم واحد على الأقل',
      'character_long':'ثمانية أحرف على الأقل',
      'or_sign_with':'او سجل الدخول عن طريق',
      'by_logging':'بتسجيل الدخول، أنت توافق على شروطنا',
      'terms_conditions':'الشروط و الاحكام',
      'and':'و',
      'privacy_policy':'سياسة الخصوصية.',
      'dont_have_account':'لا تملك حسابًا؟',
      'sign_up':'إنشاء حساب',
      'least_special_character':'حرف خاص واحد على الأقل',
      'create_account':'إنشاء حساب',
      'sign':'سجّل الآن وابدأ في استكشاف كل ما يقدّمه تطبيقنا. نحن متحمسون للترحيب بك في مجتمعنا!',
      'name':'الاسم',
      'first_name':'الاسم الأول',
      'last_name':'اسم العائلة',
      'date_of_birth':'تاريخ الميلاد',
      'name_is_required':'الاسم مطلوب',
      'first_name_required':'الاسم الأول مطلوب',
      'last_name_required':'اسم العائلة مطلوب',
      'birth_date_required':'تاريخ الميلاد مطلوب',
      'please_enter_validate_email':'يرجى إدخال بريد إلكتروني صالح',
      'phone':'الهاتف',
      'phone_required':'رقم الهاتف مطلوب',
      'male':'ذكر',
      'female':'انثى',
      'register':'انشاء حساب',
      'confirm_password':'تأكيد كلمة المرور',
      'the_confirm_password':'يجب أن تتطابق كلمة المرور المؤكدة مع كلمة المرور',
      'already_have':'هل لديك حساب بالفعل؟',
      'sign_in':'تسجيل الدخول',
      'hi':'مرحبا',
      'find_your_doctor':'اعثر على طبيبك',
      'search':'ابحث.....',
      'chat_with_doctors':'استشر الأطباء',
      'our_services':'خدماتنا اليومية',
      'test_your_self_now':'اختبر صحتك الآن',
      'book_now':'احجز الآن مع أفضل الأطباء',
      'populars_doctors':'اشهر الدكاترة',
      'physical_therapy':'العلاج الطبيعي',
      'see_all':'عرض الكل',
      'search_screen':'شاشة البحث',
      'sorry_find':'عذرًا، لم نتمكن من العثور على أي نتائج تطابق بحثك.',
  'doctor_details':' تفاصيل الطبيب',
      'book_now_':'احجز الآن',
      'services':'الخدمات',
      'patient_care':' رعاية المرضى يجب أن تكون الأولوية القصوى.',
      'profile':'الملف الشخصي',
      'log_out':'تسجيل الخروج',
      'settings':'الإعدادات',
      'settings_quick_access':'وصول سريع للإعدادات',
      'settings_quick_access_description':'تحكم باللغة والملف الشخصي والأدوية وتسجيل الخروج من مكان واحد.',
      'add_medicine':'إضافة دواء',
      'medicine_information':'معلومات الدواء',
      'medicine_name':'اسم الدواء',
      'e.g_panadol':'مثال: بانادول',
      'dosage':'الجرعة',
      'e.g_pill':'مثال: حبة واحدة',
      'reminder_time':'وقت التذكير',
      'select_reminder_time':'اختر وقت التذكير',
      'save_reminder':'حفظ التذكير',
      'please_fill_fields':'يرجى ملء جميع الحقول',
      'time_to_take':'وقت تناول',
      'medicine_reminder_scheduled':'تم جدولة تذكير الدواء',
      'my_medicines':'أدويتي',
      'no_medicines_yet':'لا توجد أدوية بعد!!',
      'add_your_medicines':'أضف أدويتك للبدء في تتبع الجرعات والتذكيرات.',
      'that_why_some':'ولهذا السبب يوجد نظام تذكير بالمواعيد',
      'if_run_your':'إذا كنت تدير عيادتك، فأنت تعرف مدى الإحباط',
      'appointment':'موعد',
      'appointment_for':'موعد ل',
      'patient_name':'اسم المريض',
      'contact_number':'رقم الاتصال',
      'select_date':'اختر التاريخ',
      'choose_appointment_date':'اختر تاريخ الموعد',
      'select_time':'اختر الوقت',
      'contact_number_required':'رقم الاتصال مطلوب',
      'please_select_date':';يرجى اختيار التاريخ',
      'please_select_time':'يرجى اختيار الوقت',
      'appointment_booked_successfully':'تم حجز الموعد بنجاح',
      'confirm_appointment':'تأكيد الموعد',
      'type_message':'اكتب رسالة...',
      'chat':'محادثة',
      'about_disease':'عن مرض باركنسون',
      'parkinson_effectively':'مرض باركنسون هو اضطراب تنكسي عصبي يؤثر على الحركة. الكشف المبكر هو المفتاح لإدارة الأعراض بشكل فعال.',
      'tap_talk_about':'اضغط للتحدث عن مرض باركنسون',
      'self_assessment_tests':'اختبارات التقييم الذاتي',
      'tremor_test':'اختبار الرعشة',
      'check_your_tremors':'تحقق من رعشة اليد وتكرار الاهتزاز',
      'balance_gait_test':'اختبار التوازن والمشي',
      'evaluate_your_balance':'قم بتقييم توازنك ونمط مشيك',
      'voice_speech':'اختبار الصوت والكلام',
      'analyze_your_speech':'حلل كلامك للكشف عن مؤشرات مرض باركنسون',
      'tips_advice':'نصائح وإرشادات',
      'stay_active':'ابقَ نشيطًا',
      'exercise':'مارس التمارين بانتظام لتحسين الحركة والتوازن',
      'healthy_diet':'نظام غذائي صحي',
      'drink_water':'اشرب الماء قبل الوجبات',
      'hydration_reminder':'اشرب ٨ أكواب من الماء يومياً',
      'portion_timing':'تناول وجبات متوازنة كل ٣ إلى ٤ ساعات',
      'balanced_plate':'طبق متوازن مليء بالفواكه والخضروات',
      'food_categories_section':'فئات الأطعمة',
      'quick_hints_section':'نصائح سريعة',
      'vegetables':'خضروات',
      'proteins':'بروتينات',
      'grains':'حبوب',
      'healthy_fats':'دهون صحية',
      'tomato':'طماطم',
      'carrot':'جزر',
      'cucumber':'خيار',
      'lettuce':'خس',
      'chicken':'دجاج',
      'fish':'سمك',
      'eggs':'بيض',
      'beans':'فاصوليا',
      'rice':'أرز',
      'oats':'شوفان',
      'bread':'خبز',
      'pasta':'باستا',
      'olive_oil':'زيت زيتون',
      'avocado':'أفوكادو',
      'nuts':'مكسرات',
      'memory_test':'اختبار الذاكرة',
      'memory_test_description':'اختبر قدرتك على تذكر الصور المتشابهة بعد أن تُغطى.',
      'memory_test_instruction':'ستعرض ١٠ بطاقات في البداية، اتذكر أماكنها ثم اختر البطاقتين المتطابقتين من ٥ أزواج.',
      'memory_test_retry':'أعد تشغيل الاختبار',
      'memory_test_result_title':'مدى تأثير مرض باركنسون',
      'memory_test_result_message':'الوقت: {0} ثانية. {1}',
      'memory_test_result_low':'تأثير بسيط على الذاكرة.',
      'memory_test_result_medium':'تأثير متوسط، راقب تطور الأداء.',
      'memory_test_result_high':'تأثير كبير؛ يرجى مراجعة الطبيب.',
      'test_results':'نتائج الاختبارات',
      'summary_title':'متابعة الأداء',
      'summary_description':'متابعة النسبة المئوية لكل جانب من الجوانب السابقة.',
      'summary_total':'النتيجة الكلية',
      'summary_overall':'إجمالي',
      'summary_timestamp':'آخر تحديث: {0}',
      'physical':'بدني',
      'emotional':'عاطفي',
      'cognitive':'معرفي',
      'tremor':'الرعشة',
      'memory':'الذاكرة',
      'voice':'الصوت',
      'general_question':'أسئلة عامة',
      'general_question_description':'حدد درجة التأثير لكل جانب من يومك.',
      'general_question_mood':'وصف المزاج',
      'general_question_sleep':'وصف النوم',
      'general_question_appetite':'وصف الشهية',
      'general_question_concentration':'وصف التركيز',
      'general_option_awful':'سيء للغاية',
      'general_option_poor':'ضعيف',
      'general_option_ok':'متوسط',
      'general_option_good':'جيد',
      'general_option_great':'رائع',
      'general_question_save':'حفظ الاختبار',
      'general_question_saved':'تم حفظ الإجابات',
      'memory_test_result_title':'مدى تأثير مرض باركنسون',
      'memory_test_result_message':'الوقت: {0} ثانية. {1}',
      'memory_test_result_low':'تأثير بسيط على الذاكرة.',
      'memory_test_result_medium':'تأثير متوسط، راقب تطور الأداء.',
      'memory_test_result_high':'تأثير كبير؛ يرجى مراجعة الطبيب.',
      'meal_timing':'توقيت الوجبات',
      'balanced_diet_hint':'نمط غذائي متوازن',
      'calories':'السعرات الحرارية',
      'healthy_plate_title':'مكونات الطبق الصحي الوطني',
      'healthy_plate_description':'قسم طبقك إلى الخضار والبروتينات والنشويات، وأضف الدهون الصحية والماء.',
      'half_plate_veggies':'نصف الطبق خضار وألياف',
      'veggies_tip':'املأ نصف طبقك بالخضار الملونة والألياف.',
      'quarter_plate_protein':'ربع الطبق بروتينات',
      'protein_tip':'اختر البروتينات الخالية من الدهون والمصادر النباتية.',
      'quarter_plate_grains':'ربع الطبق نشويات',
      'grains_tip':'استخدم الحبوب الكاملة لتزويدك بالطاقة المستمرة.',
      'healthy_plate_oil':'الدهون الصحية',
      'olive_oil_tip':'استخدم زيت الزيتون أو مصادر الدهون الجيدة بحذر.',
      'balanced_diet':'يمكن أن يساعد النظام الغذائي المتوازن في إدارة الأعراض وتحسين الصحة العامة',
      'parkinson_tests':'مرض الباركنسون',
      'this_test':'هذا الاختبار ليس تشخيصًا طبيًا.\nيرجى استشارة الطبيب.',
      'low_tremor_detected':'تم اكتشاف رعشة منخفضة',
      'moderate_tremor_detected':'تم اكتشاف رعشة متوسطة',
      'high_tremor_detected':'تم اكتشاف رعشة عالية',
      'hold_your_phone':'أمسك هاتفك بثبات بيد واحدة وحاول البقاء ساكنًا أثناء الاختبار.',
      'parknson_videos':'فيديوهات باركنسون',
      'educational':'مقاطع فيديو تعليمية وتمارين مصممة لدعم مرضى باركنسون أثناء العلاج والأنشطة اليومية.',
      'notifications':'الإشعارات',
      'doctor':'دكتور',
      'place_your_phone':'ضع هاتفك عند مستوى الخصر أو أمسكه بيدك.\nامشِ ببطء في خط مستقيم أو قف في مكانك.',
      'testing':'جارٍ الاختبار...',
      'start_test':'بدء الاختبار',
      'this_tests':'هذا الاختبار ليس تشخيصًا طبيًا.\nيرجى استشارة الطبيب.',
      'recording_duration':'مدة التسجيل:',
      'sec':'ثانية',
      'estimated_speech_rate':'معدل الكلام المقدر:',
      'words/min':'كلمة/دقيقة',
      'note_simple':'ملاحظة: هذا اختبار محلي بسيط. للحصول على تحليل مفصل، يرجى استشارة الطبيب.',
      'stop_recording':'إيقاف التسجيل',
      'start_recording':'بدء التسجيل',
      'eat_more_fruits_vegetables':'تناول المزيد من الفواكه والخضروات',
      'include_variety':'اشمل مجموعة متنوعة من الفواكه والخضروات الملونة يوميًا.',
      'include_whole_grains':'اشمل الحبوب الكاملة',
      'brown_rice_oat':'الأرز البني، الشوفان، والقمح الكامل يمكن أن يحسنوا الهضم ويزيدوا الطاقة.',
      'healthy_proteins':'البروتينات الصحية',
      'include_fish':'اشمل السمك، اللحوم الخالية من الدهون، البيض، والبقوليات.',
      'limit_processed_foods':'قلل من الأطعمة المصنعة',
      'avoid_high_suga':'تجنب الأطعمة المصنعة عالية السكر والملح.',
      'daily_stretching':'تمارين الإطالة اليومية',
      'perform_gentle':'قم بأداء تمارين إطالة خفيفة لتحسين المرونة.',
      'balance_exercises':'تمارين التوازن',
      'practice_standing':'تمرن على الوقوف على ساق واحدة أو المشي من كعب إلى أصابع القدم.',
      'strength_training':'تمارين تقوية العضلات',
      'use_light_weight':'استخدم أوزانًا خفيفة أو أشرطة المقاومة للحفاظ على قوة العضلات.',
      'regular_walking':'المشي المنتظم',
      'walk_daily_improve':'امشِ يوميًا لتحسين الحركة وصحة القلب والأوعية الدموية.',
      'appointments':'المواعيد',
      'Chats':'الدردشات',
      'doctor_dashboard':'لوحة تحكم الطبيب',
      'no_appointments_yet':'لا توجد مواعيد حتى الآن!',
      'you_currently':'لا توجد لديك مواعيد للمرضى حالياً بمجرد أن يطلب أحد المرضى موعدًا، سيظهر هنا',
      'refresh':'تحديث',
      'doctor_appointments':'حجوزات الدكتور',
      'time':'الوقت',
      'date':'التاريخ',
      'no_messages_yet':'لا توجد رسائل بعد',





      'edit_medicine':'تعديل الدواء',
      'delete_medicine':'حذف الدواء',
      'delete_medicine_confirmation':'هل تريد حذف هذا الدواء وإلغاء التذكير المرتبط به؟',
      'medicine_deleted':'تم حذف الدواء',
      'medicine_updated':'تم تحديث الدواء',
      'save_changes':'حفظ التعديلات',
      'cancel':'إلغاء',
    },
    'en':{
      'no_messages_yet':'No messages yet',
      'date':'Date',

          'time':'Time',
      'doctor_appointments':'Doctor Appointments',
      'refresh':'Refresh',
      'you_currently':'You currently have no patient appointments.\n Once a patient requests, it will appear here.',
      'no_appointments_yet':'No Appointments Yet!',
      'doctor_dashboard':'Doctor Dashboard',
      'Chats':'Chats',
      'appointments':'Appointments',
          'walk_daily_improve':'Walk daily to improve mobility and cardiovascular health.',
      'regular_walking':'Regular Walking',
      'use_light_weight':'Use light weights or resistance bands to maintain muscle strength.',
      'strength_training':'Strength Training',
      'practice_standing':'Practice standing on one leg or heel-to-toe walking.',
      'balance_exercises':'Balance Exercises',
      'perform_gentle':'Perform gentle stretches to improve flexibility.',
      'daily_stretching':'Daily Stretching',
      'avoid_high_suga':'Avoid high-sugar and high-salt processed foods.',
      'limit_processed_foods':'Limit Processed Foods',
      'include_fish':'Include fish, lean meats, eggs, and legumes.',
      'healthy_proteins':'Healthy Proteins',
      'brown_rice_oat':'Brown rice, oats, and whole wheat can improve digestion and energy.',
      'include_whole_grains':'Include Whole Grains',
      'include_variety':'Include a variety of colorful fruits and vegetables daily.',
      'eat_more_fruits_vegetables':'Eat More Fruits & Vegetables',
      'start_recording':'Start Recording',
      'stop_recording':'Stop Recording',
      'note_simple':'Note: This is a simple local test. For detailed analysis, consult a doctor.',
      'words/min':'Words/Min',
      'estimated_speech_rate':'Estimated Speech Rate:',
      'sec':'Sec',
          'recording_duration':'Recording Duration:',
      'this_tests':'This test is not a medical diagnosis.\nPlease consult a doctor.',
      'start_test':'Start Test',
      'testing':'Testing...',
      'place_your_phone':'Place your phone at waist level or hold it in your hand.\nWalk slowly in a straight line or stand still.',
      'doctor':'Doctor',
      'notifications':'Notifications',
      'educational':'Educational and exercise videos designed to support Parkinson’s patients during treatment and daily activities.',
      'parknson_videos':'Parknson Videos',
      'hold_your_phone':'Hold your phone steady in one hand and remain still during the test.',
      'high_tremor_detected':'High tremor detected',
      'moderate_tremor_detected':'Moderate tremor detected',
      'low_tremor_detected':'Low tremor detected',
      'this_test':'This test is not a medical diagnosis.\nPlease consult a doctor.',
      'parkinson_tests':'Parkinson Tests',
      'balanced_diet':'A balanced diet can help manage symptoms and overall health',
      'healthy_diet':'Healthy Diet',
      'drink_water':'Drink water before meals',
      'hydration_reminder':'Aim for 8 cups of water daily',
      'portion_timing':'Enjoy balanced meals every 3-4 hours',
      'balanced_plate':'A balanced plate of grains, proteins & greens',
      'food_categories_section':'Food Categories',
      'quick_hints_section':'Quick Hints',
      'vegetables':'Vegetables',
      'proteins':'Proteins',
      'grains':'Grains',
      'healthy_fats':'Healthy Fats',
      'tomato':'Tomato',
      'carrot':'Carrot',
      'cucumber':'Cucumber',
      'lettuce':'Lettuce',
      'chicken':'Chicken',
      'fish':'Fish',
      'eggs':'Eggs',
      'beans':'Beans',
      'rice':'Rice',
      'oats':'Oats',
      'bread':'Bread',
      'pasta':'Pasta',
      'olive_oil':'Olive Oil',
      'avocado':'Avocado',
      'nuts':'Nuts',
      'meal_timing':'Meal Timing',
      'balanced_diet_hint':'Balanced Diet',
      'calories':'Calories',
      'memory_test':'Memory Test',
      'memory_test_description':'Test how well you can remember matching images after they flip.',
      'memory_test_instruction':'A grid of 10 cards hides 5 matching pairs. Reveal two cards at a time and find all pairs before they flip back.',
      'memory_test_retry':'Restart Game',
      'memory_test_result_title':'Parkinson’s impact',
      'memory_test_result_message':'Time: {0}s. {1}',
      'memory_test_result_low':'Memory impact seems mild.',
      'memory_test_result_medium':'Noticeable impact; keep watching.',
      'memory_test_result_high':'Significant impact; consult your doctor.',
      'test_results':'Test Results',
      'summary_title':'Track your total fitness',
      'summary_description':'See the percentage for each domain in one place.',
      'summary_total':'Total Score',
      'summary_overall':'Overall',
      'summary_timestamp':'Last updated: {0}',
      'physical':'Physical',
      'emotional':'Emotional',
      'cognitive':'Cognitive',
      'tremor':'Tremor',
      'memory':'Memory',
      'voice':'Voice',
      'general_question':'General Questions',
      'general_question_description':'Select how each part of your day has been.',
      'general_question_mood':'Describe your mood',
      'general_question_sleep':'Describe your sleep',
      'general_question_appetite':'Describe your appetite',
      'general_question_concentration':'Describe your concentration',
      'general_option_awful':'Awful',
      'general_option_poor':'Poor',
      'general_option_ok':'Ok',
      'general_option_good':'Good',
      'general_option_great':'Great',
      'general_question_save':'Save Test',
      'general_question_saved':'Answers saved',
      'healthy_plate_title':'National Healthy Plate Components',
      'healthy_plate_description':'Split your plate into vegetables, proteins, grains, and a splash of healthy fats plus water.',
      'half_plate_veggies':'Half plate vegetables & fiber',
      'veggies_tip':'Fill half your plate with colorful vegetables and fiber-rich foods.',
      'quarter_plate_protein':'Quarter plate proteins',
      'protein_tip':'Pick lean and plant-based proteins for muscle health.',
      'quarter_plate_grains':'Quarter plate whole grains',
      'grains_tip':'Choose whole grains to fuel steady energy throughout the day.',
      'healthy_plate_oil':'Healthy fats',
      'olive_oil_tip':'Dress meals with olive oil or nourishing fats in moderation.',
      'exercise':'Exercise regularly to improve mobility and balance.',
      'stay_active':'Stay Active',
      'tips_advice':'Tips & Advice',
      'analyze_your_speech':'Analyze your speech for Parkinson’s indicators.',
      'voice_speech':'Voice & Speech Test',
      'evaluate_your_balance':'Evaluate your balance and walking patterns.',
      'balance_gait_test':'Balance & Gait Test',
      'check_your_tremors':'Check your hand tremors and shaking frequency.',
      'tremor_test':'Tremor Test',
      'self_assessment_tests':'Self-Assessment Tests',
      'tap_talk_about':'Tap to Talk About Parkinson',
      'parkinson_effectively':'Parkinson’s disease is a neurodegenerative disorder that affects movement. Early detection is key to managing symptoms effectively.',
      'about_disease':'About Parkinson\'s Disease',
      'chat':'Chat',
      'type_message':'Type a message...',
      'confirm_appointment':'Confirm Appointment',
      'appointment_booked_successfully':'Appointment booked successfully',
      'please_select_time':'Please Select Time',
      'please_select_date':'Please Select Date',
      'contact_number_required':'Contact Number is Required',
      'select_time':'Select Time',
      'choose_appointment_date':'Choose Appointment Date',
      'select_date':'Select Date',
      'contact_number':'Contact Number',
      'patient_name':'Patient Name',
      'appointment_for':'Appointment For',
      'appointment':'Appointment',
      'if_run_your':'If you run your practice you know how frustrating',
      'that_why_some':'That’s why some of appointment reminder system.',
      'add_your_medicines':'Add your medicines to start tracking your doses and reminders.',
  'no_medicines_yet':'No medicines yet!',
  'my_medicines':'My Medicines',
      'edit_medicine':'Edit Medicine',
      'delete_medicine':'Delete Medicine',
      'delete_medicine_confirmation':'Do you want to delete this medicine and cancel its reminder?',
      'medicine_deleted':'Medicine deleted',
      'medicine_updated':'Medicine updated',
      'save_changes':'Save Changes',
      'cancel':'Cancel',
      'medicine_reminder_scheduled':'Medicine reminder scheduled',
      'time_to_take':'Time to take',
      'please_fill_fields':'Please fill all fields',
      'save_reminder':'Save Reminder',
      'select_reminder_time':'Select reminder time',
      'reminder_time':'Reminder Time',
  'e.g_pill':'e.g. 1 pill',
  'dosage':'Dosage',
  'e.g_panadol':'e.g. Panadol',
  'medicine_name':'Medicine Name',
      'medicine_information':'Medicine Information',
  'add_medicine':'Add Medicine',
  'settings':'Settings',
      'settings_quick_access':'Quick Settings Access',
      'settings_quick_access_description':'Manage language, profile, medicines, and logout from one place.',
  'log_out':'Log Out',
      'profile':'Profile',
      'patient_care':'Patient care should be the number one priority.',
  'services':'Services',
  'book_now_':'Book Now',
      'doctor_details':'Doctor Details',
  'sorry_find':'Sorry, we couldn’t find anything that matches your search.',
  'search_screen':'Search Screen',
  'see_all':'See All',
      'populars_doctors':'Populars Doctors',
      'physical_therapy':'Physical Therapy',
      'book_now':'Book now with the best doctors',
      'test_your_self_now':'Test Your Self Now',
      'our_services':'Daily Services',
      'chat_with_doctors':'Chat With Doctors',
      'search':'Search.....',
      'find_your_doctor':'Find Your Doctor',
      'hi':'Hi',
      'sign_in':'Sign In',
      'already_have':'Already have an account yet?',
      'the_confirm_password':'The confirm password must be like password',
      'confirm_password':'Confirm Password',
      'register':'Register',
      'female':'Female',
      'male':'Male',
  'phone_required':'Phone is required',
      'phone':'Phone',
      'please_enter_validate_email':'Please enter validate email',
      'name_is_required':'Name is Required',
      'name':'name',
      'first_name':'First Name',
      'last_name':'Last Name',
      'date_of_birth':'Date of Birth',
      'first_name_required':'First name is required',
      'last_name_required':'Last name is required',
      'birth_date_required':'Date of birth is required',
      'sign':'Sign up now and start exploring all that our app has to offer. We\'re excited to welcome you to our community!',
      'create_account':'Create Account',
      'least_special_character':'At least 1 special character',
      'sign_up':'Sign Up',
      'dont_have_account':'Don\'t have an Account?',
      'privacy_policy':'PrivacyPolicy.',
      'and':'and',
      'terms_conditions':'Terms & Conditions',
      'by_logging':'By logging, you agree to our',
      'or_sign_with':'Or sign in with',
      'character_long':'At least 8 character long',
      'number':'At least 1 number',
      'special_character':'At least 1 special character',
      'uppercase_letter':'At least 1 uppercase letter',
      'lowercase_letter':'At least 1 lowercase letter',
      'login':'Login',
      'forgot_password':'Forgot Password?',
      'password_terms':'Please follow the password terms',
      'valid_email':'Please enter a valid email',
      'password':'Password',
      'email':'Email',
      'language':'Language',
      'arabic':'Arabic',
      'english':'English',
      'parkinson':'Parkinson',
      'best_doctor_appointment_app':'Best Doctor Appointment App',
      'manage_schedule':'Manage and schedule all of your medical appointments easily with Docdoc to get a new experience.',
      'get_started':'Get Started',
      'welcome_back':'Welcome Back',
      'we_are_excited':'We\'re excited to have you back, can\'t wait to see what you\'ve been up to since you last logged in.'

    }
  };

}

