import 'package:get/get.dart';

class Strings extends Translations{
  @override

  Map<String, Map<String, String>> get keys =>{
    'ar':{
      'language':'اللغة',
      'arabic':'االعربية',
      'english':'الانجليزية',
      'parkinson':'الباركنسون',
      'best_doctor_appointment_app':'أفضل تطبيق لحجز المواعيد الطبية',
      'manage_schedule':'قم بإدارة وجدولة جميع مواعيدك الطبية بسهولة مع Docdoc للحصول على تجربة جديدة.',
      'get_started':'ابدأ الآن',
      'welcome_back':'مرحباً بعودتك',
      'we_are_excited':'نحن متحمسون لعودتك، ولا يسعنا الانتظار لرؤية ما كنت تفعله منذ آخر تسجيل دخول لك',
      'email':'البريد الاكتروني',
      'password':'كلمة المرور',
      'valid_email':'يرجى ادخال بريد الاكتروني فعال',
      'password_terms':'يرجى الالتزام بشروط كلمة المرور',
      'forgot_password':'هل نسيت كلمة السر ؟',
      'login':'تسجيل الدخول',
      'lowercase_letter':'حرف صغير واحد على الأقل',
      'uppercase_letter':'حرف كبير واحد على الأقل',
      'special_character':'رمز خاص واحد على الأقل',
      'number':'رقم واحد على الأقل',
      'character_long':'ثمانية أحرف على الأقل',
      'or_sign_with':'او سجل الدخول عن طريق',
      'by_logging':'بتسجيل الدخول، أنت توافق على شروطنا',
      'terms_conditions':'الشروط و الاحكام',
      'and':'و',
      'privacy_policy':'سياسة الخصوصية.',
      'dont_have_account':'لا تملك حسابًا؟',
      'sign_up':'إنشاء حساب',
      'least_special_character':'حرف خاص واحد على الأقل',
      'create_account':'إنشاء حساب',
      'sign':'سجّل الآن وابدأ في استكشاف كل ما يقدّمه تطبيقنا. نحن متحمسون للترحيب بك في مجتمعنا!',
      'name':'الاسم',
      'name_is_required':'الاسم مطلوب',
      'please_enter_validate_email':'يرجى إدخال بريد إلكتروني صالح',
      'phone':'الهاتف',
      'phone_required':'رقم الهاتف مطلوب',
      'male':'ذكر',
      'female':'انثى',
      'register':'انشاء حساب',
      'confirm_password':'تأكيد كلمة المرور',
      'the_confirm_password':'يجب أن تتطابق كلمة المرور المؤكدة مع كلمة المرور',
      'already_have':'هل لديك حساب بالفعل؟',
      'sign_in':'تسجيل الدخول',
      'hi':'مرحبا',
      'find_your_doctor':'اعثر على طبيبك',
      'search':'ابحث.....',
      'chat_with_doctors':'استشر الأطباء',
      'our_services':'خدماتنا',
      'test_your_self_now':'اختبر صحتك الآن',
      'book_now':'احجز الآن مع أفضل الأطباء',
      'populars_doctors':'اشهر الدكاترة',
      'see_all':'عرض الكل',
      'search_screen':'شاشة البحث',
      'sorry_find':'عذرًا، لم نتمكن من العثور على أي نتائج تطابق بحثك.',
  'doctor_details':' تفاصيل الطبيب',
      'book_now_':'احجز الآن',
      'services':'الخدمات',
      'patient_care':' رعاية المرضى يجب أن تكون الأولوية القصوى.',
      'profile':'الملف الشخصي',
      'log_out':'تسجيل الخروج',
      'settings':'الإعدادات',
      'add_medicine':'إضافة دواء',
      'medicine_information':'معلومات الدواء',
      'medicine_name':'اسم الدواء',
      'e.g_panadol':'مثال: بانادول',
      'dosage':'الجرعة',
      'e.g_pill':'مثال: حبة واحدة',
      'reminder_time':'وقت التذكير',
      'select_reminder_time':'اختر وقت التذكير',
      'save_reminder':'حفظ التذكير',
      'please_fill_fields':'يرجى ملء جميع الحقول',
      'time_to_take':'وقت تناول',
      'medicine_reminder_scheduled':'تم جدولة تذكير الدواء',
      'my_medicines':'أدويتي',
      'no_medicines_yet':'لا توجد أدوية بعد!!',
      'add_your_medicines':'أضف أدويتك للبدء في تتبع الجرعات والتذكيرات.',
















    },
    'en':{
      'add_your_medicines':'Add your medicines to start tracking your doses and reminders.',
  'no_medicines_yet':'No medicines yet!',
  'my_medicines':'My Medicines',
      'medicine_reminder_scheduled':'Medicine reminder scheduled',
      'time_to_take':'Time to take',
      'please_fill_fields':'Please fill all fields',
      'save_reminder':'Save Reminder',
      'select_reminder_time':'Select reminder time',
      'reminder_time':'Reminder Time',
  'e.g_pill':'e.g. 1 pill',
  'dosage':'Dosage',
  'e.g_panadol':'e.g. Panadol',
  'medicine_name':'Medicine Name',
      'medicine_information':'Medicine Information',
  'add_medicine':'Add Medicine',
  'settings':'Settings',
  'log_out':'Log Out',
      'profile':'Profile',
      'patient_care':'Patient care should be the number one priority.',
  'services':'Services',
  'book_now_':'Book Now',
      'doctor_details':'Doctor Details',
  'sorry_find':'Sorry, we couldn’t find anything that matches your search.',
  'search_screen':'Search Screen',
  'see_all':'See All',
      'populars_doctors':'Populars Doctors',
      'book_now':'Book now with the best doctors',
      'test_your_self_now':'Test Your Self Now',
      'our_services':'Our Services',
      'chat_with_doctors':'Chat With Doctors',
      'search':'Search.....',
      'find_your_doctor':'Find Your Doctor',
      'hi':'Hi',
      'sign_in':'Sign In',
      'already_have':'Already have an account yet?',
      'the_confirm_password':'The confirm password must be like password',
      'confirm_password':'Confirm Password',
      'register':'Register',
      'female':'Female',
      'male':'Male',
  'phone_required':'Phone is required',
      'phone':'Phone',
      'please_enter_validate_email':'Please enter validate email',
      'name_is_required':'Name is Required',
      'name':'name',
      'sign':'Sign up now and start exploring all that our app has to offer. We\'re excited to welcome you to our community!',
      'create_account':'Create Account',
      'least_special_character':'At least 1 special character',
      'sign_up':'Sign Up',
      'dont_have_account':'Don\'t have an Account?',
      'privacy_policy':'PrivacyPolicy.',
      'and':'and',
      'terms_conditions':'Terms & Conditions',
      'by_logging':'By logging, you agree to our',
      'or_sign_with':'Or sign in with',
      'character_long':'At least 8 character long',
      'number':'At least 1 number',
      'special_character':'At least 1 special character',
      'uppercase_letter':'At least 1 uppercase letter',
      'lowercase_letter':'At least 1 lowercase letter',
      'login':'Login',
      'forgot_password':'Forgot Password?',
      'password_terms':'Please follow the password terms',
      'valid_email':'Please enter a valid email',
      'password':'Password',
      'email':'Email',
      'language':'Language',
      'arabic':'Arabic',
      'english':'English',
      'parkinson':'Parkinson',
      'best_doctor_appointment_app':'Best Doctor Appointment App',
      'manage_schedule':'Manage and schedule all of your medical appointments easily with Docdoc to get a new experience.',
      'get_started':'Get Started',
      'welcome_back':'Welcome Back',
      'we_are_excited':'We\'re excited to have you back, can\'t wait to see what you\'ve been up to since you last logged in.'

    }
  };

}